title: Your awesome title
theme: minima
author: Belinda Zhang
email: belindazhang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Belinda. Here is some basic info about me :)
# social links
twitter_username: beilyndao # DO NOT include the @ character, or else the build will fail!
github_username:  bzhang123123 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
